name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint anybadge
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        score=$(pylint --exit-zero $(git ls-files '*.py') | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p')
        anybadge -l pylint -v $score -f badge.svg 2=red 4=orange 8=yellow 10=green
    - name: Store badge
      uses: actions/upload-artifact@v3
      with:
        name: badge
        path: badge.svg
